from .azure_embedding_service import AzureEmbeddingService
from .azure_blob_service import AzureBlobService
from .azure_speech_client import AzureSpeechClient
from .azure_vector_service import AzureVectorService