import argparse
import json
import secrets
import sys # Import sys
from enum import Enum
import logging # Import logging

logging.basicConfig(level=logging.INFO) # Setup basic logging

class EncryptionAlgorithm(Enum):
    # Symmetric Algorithms (supported by this script)
    HS256 = 'HS256'
    HS384 = 'HS384'
    HS512 = 'HS512'
    # Asymmetric Algorithms (NOT generated by this script)
    ES256 = 'ES256'
    ES384 = 'ES384'
    ES512 = 'ES512'
    RS256 = 'RS256'
    # Add others if needed


def generate_symmetric_keys(algorithm: EncryptionAlgorithm):
    """Generates a symmetric secret key for HS algorithms."""
    if algorithm not in {EncryptionAlgorithm.HS256, EncryptionAlgorithm.HS384, EncryptionAlgorithm.HS512}:
         raise ValueError(f"This function only supports HS256, HS384, HS512. Algorithm requested: {algorithm}")

    KEY_SIZES = {
        EncryptionAlgorithm.HS256: 32,  # 256-bit key
        EncryptionAlgorithm.HS384: 48,  # 384-bit key
        EncryptionAlgorithm.HS512: 64  # 512-bit key
    }
    secret_key = secrets.token_hex(KEY_SIZES[algorithm])
    # For symmetric keys, private and public concepts merge into one secret
    return secret_key, secret_key


if __name__ == '__main__':
    arg_parser = argparse.ArgumentParser(
        description="Generate secrets for JWT signing (Symmetric Keys Only - HS*)."
    )
    arg_parser.add_argument('--output', '-O', type=str, default='./jwt_secret.json',
                            help="Output file path for the JSON secret.")
    # Default to HS256 as this script primarily supports symmetric keys
    arg_parser.add_argument('--algorithm', '-A', type=EncryptionAlgorithm,
                            choices=[EncryptionAlgorithm.HS256, EncryptionAlgorithm.HS384, EncryptionAlgorithm.HS512],
                            default=EncryptionAlgorithm.HS256,
                            help="Symmetric algorithm to generate a key for (HS256, HS384, HS512). Default: HS256.")
    args = arg_parser.parse_args()

    # --- WARNING ---
    logging.warning("-" * 60)
    logging.warning("WARNING: This script ONLY generates keys suitable for SYMMETRIC algorithms (HS256, HS384, HS512).")
    logging.warning("If your application requires an ASYMMETRIC algorithm (like ES256, ES512, RS256), "
                "you MUST generate the keys using external tools like 'openssl' and manually create/edit the output JSON.")
    logging.warning("-" * 60)

    if args.algorithm not in {EncryptionAlgorithm.HS256, EncryptionAlgorithm.HS384, EncryptionAlgorithm.HS512}:
        logging.error(f"Algorithm '{args.algorithm.value}' is asymmetric and cannot be generated by this script.")
        logging.info("To generate keys for ES512, use openssl:")
        logging.info("1. openssl ecparam -name secp521r1 -genkey -noout -out es512_private_key.pem")
        logging.info("2. openssl ec -in es512_private_key.pem -pubout -out es512_public_key.pem")
        logging.info(f"Then manually create '{args.output}' with algorithm='ES512' and copy the PEM file contents.")
        sys.exit(1)

    # Generate symmetric keys
    private_key, public_key = generate_symmetric_keys(args.algorithm)

    output_json = {
        "algorithm": args.algorithm.value,
        "private_key": private_key, # For HS*, this is the shared secret
        "public_key": public_key,   # For HS*, this is the same shared secret
    }

    # Save to file
    try:
        with open(args.output, 'w') as f:
            f.write(json.dumps(output_json, indent=4))
        print(f"Symmetric key for {args.algorithm.value} generated and saved to {args.output}")
        print("REMINDER: If you need ES512 or another asymmetric algorithm, ensure this file reflects keys generated externally (e.g., with openssl).")
    except IOError as e:
        logging.error(f"Failed to write secrets file to {args.output}: {e}")
        sys.exit(1)